import { describe, it, expect } from 'vitest'
import { deleteCashMovement, LinkedMovementError } from '../cash-engine'

// ── Fake Supabase ────────────────────────────────────────────────────────────

interface QueryCall {
  table: string
  ops: Array<[string, ...unknown[]]>
}

function fakeSupabase(config: {
  movement?: { id: string; transaction_id: string | null } | null
  movements?: unknown[]
}) {
  const calls: QueryCall[] = []
  return {
    calls,
    from(table: string) {
      const entry: QueryCall = { table, ops: [] }
      calls.push(entry)
      const q: Record<string, unknown> = {}
      for (const m of ['select', 'eq', 'order', 'delete', 'upsert', 'insert', 'not']) {
        q[m] = (...args: unknown[]) => {
          entry.ops.push([m, ...args])
          return q
        }
      }
      q.maybeSingle = async () => {
        entry.ops.push(['maybeSingle'])
        return { data: config.movement ?? null, error: null }
      }
      q.single = async () => {
        entry.ops.push(['single'])
        return { data: { user_id: 'u1', balance: 0 }, error: null }
      }
      q.then = (onFulfilled: (v: unknown) => unknown) => {
        const isSelect = entry.ops.some(([m]) => m === 'select')
        const result = isSelect ? { data: config.movements ?? [], error: null } : { error: null }
        return Promise.resolve(result).then(onFulfilled)
      }
      return q
    },
  }
}

function deletesOn(calls: QueryCall[], table: string): QueryCall[] {
  return calls.filter((c) => c.table === table && c.ops.some(([m]) => m === 'delete'))
}

// ── Tests ────────────────────────────────────────────────────────────────────

describe('deleteCashMovement — transaction-linked guard', () => {
  it('refuses to delete a movement generated by a transaction', async () => {
    // Arrange — a COMPRA's cash leg: deleting it desyncs the ledger forever
    const supabase = fakeSupabase({ movement: { id: 'm1', transaction_id: 'tx1' } })

    // Act + Assert
    await expect(
      deleteCashMovement(supabase as never, 'u1', 'm1')
    ).rejects.toBeInstanceOf(LinkedMovementError)

    // ...and nothing was deleted
    expect(deletesOn(supabase.calls, 'cash_movements')).toHaveLength(0)
  })

  it('deletes a manual movement (transaction_id NULL) and rebuilds the balance', async () => {
    // Arrange
    const supabase = fakeSupabase({ movement: { id: 'm2', transaction_id: null }, movements: [] })

    // Act
    const balance = await deleteCashMovement(supabase as never, 'u1', 'm2')

    // Assert
    expect(deletesOn(supabase.calls, 'cash_movements')).toHaveLength(1)
    expect(balance).toBeTruthy()
  })

  it('throws when the movement does not exist for this user', async () => {
    // Arrange
    const supabase = fakeSupabase({ movement: null })

    // Act + Assert
    await expect(deleteCashMovement(supabase as never, 'u1', 'nope')).rejects.toThrow()
    expect(deletesOn(supabase.calls, 'cash_movements')).toHaveLength(0)
  })
})
